"""Tests for the documentation generator, including the overview ('Start Here') page."""

from __future__ import annotations

import pytest

from codebase_teacher.generator.docs import (
    API_CHUNK_SIZE,
    generate_all_docs,
    generate_api_doc,
    generate_overview_doc,
)
from codebase_teacher.storage.artifact_store import ArtifactStore
from codebase_teacher.storage.database import Database
from codebase_teacher.storage.models import (
    AnalysisResult,
    APIEndpoint,
    DataFlow,
    InfraComponent,
)


def _make_store(tmp_path) -> tuple[ArtifactStore, Database]:
    db = Database(tmp_path / "test.db")
    project_id = db.get_or_create_project(str(tmp_path), "test_project")
    store = ArtifactStore(tmp_path / "output", db, project_id)
    return store, db


def _make_analysis() -> AnalysisResult:
    return AnalysisResult(
        project_summary="A small Flask API that manages users and sends welcome emails.",
        module_summaries={
            "app.py": "Flask entry point. Wires routes to user handlers.",
            "users.py": "User CRUD logic backed by PostgreSQL.",
            "tasks.py": "Celery tasks for sending emails.",
        },
        api_endpoints=[
            APIEndpoint(
                method="POST",
                path="/api/users",
                handler="create_user",
                file="users.py",
                description="Create a new user",
            ),
        ],
        infrastructure=[
            InfraComponent(
                type="database",
                technology="PostgreSQL",
                explanation="Relational database.",
                usage="Stores user records.",
                config="DATABASE_URL env var",
            ),
        ],
        data_flows=[
            DataFlow(
                name="User signup",
                entry_points=["POST /api/users"],
                steps=["Validate input", "Insert into DB", "Enqueue welcome email"],
                outputs=["DB write", "Celery task"],
            ),
        ],
    )


@pytest.mark.asyncio
async def test_generate_overview_doc_writes_start_here_page(mock_provider, tmp_path):
    store, db = _make_store(tmp_path)
    try:
        analysis = _make_analysis()

        path = await generate_overview_doc(mock_provider, analysis, store)

        assert path.exists()
        assert path.name == "overview.md"
        assert path.parent.name == "docs"

        content = path.read_text()
        # Template wraps the body with a title and footer
        assert "# Start Here" in content
        assert "Generated by codebase-teacher" in content
    finally:
        db.close()


@pytest.mark.asyncio
async def test_generate_overview_doc_passes_context_to_llm(mock_provider, tmp_path):
    store, db = _make_store(tmp_path)
    try:
        analysis = _make_analysis()

        await generate_overview_doc(mock_provider, analysis, store)

        # The provider should have been called with the project summary and
        # references to the other docs/surfaces so the LLM can point readers to them.
        assert len(mock_provider._calls) == 1
        user_msg = mock_provider._calls[0][-1].content
        assert "Flask API" in user_msg
        assert "PostgreSQL" in user_msg
        assert "POST /api/users" in user_msg
        # Prompt should steer the model toward a friendly 'Start Here' structure
        assert "Start Here" in user_msg or "start here" in user_msg.lower()
        assert "architecture.md" in user_msg
    finally:
        db.close()


@pytest.mark.asyncio
async def test_generate_overview_doc_handles_empty_analysis(mock_provider, tmp_path):
    store, db = _make_store(tmp_path)
    try:
        analysis = AnalysisResult()  # everything empty / default

        path = await generate_overview_doc(mock_provider, analysis, store)

        assert path.exists()
        content = path.read_text()
        assert "# Start Here" in content
    finally:
        db.close()


@pytest.mark.asyncio
async def test_generate_api_doc_chunks_many_endpoints(mock_provider, tmp_path):
    store, db = _make_store(tmp_path)
    try:
        # Create analysis with more endpoints than API_CHUNK_SIZE
        endpoints = [
            APIEndpoint(
                method="GET",
                path=f"/api/resource-{i}",
                handler=f"get_resource_{i}",
                file="routes.py",
                description=f"Get resource {i}",
            )
            for i in range(API_CHUNK_SIZE + 5)
        ]
        analysis = AnalysisResult(
            project_summary="A test project.",
            api_endpoints=endpoints,
        )

        path = await generate_api_doc(mock_provider, analysis, store)

        assert path.exists()
        assert path.name == "api-reference.md"
        # With chunking, the provider should be called multiple times
        # (one per chunk, not just once)
        assert len(mock_provider._calls) >= 2
    finally:
        db.close()


class _ScriptedProvider:
    """Test helper: returns one scripted response per call.

    After the script is exhausted, returns an empty string (simulating a
    silent LLM failure).
    """

    def __init__(self, responses: list[str]):
        self._responses = list(responses)
        self._calls: list[list] = []

    async def complete(self, messages, temperature=0.3, max_tokens=None, response_format=None):
        from codebase_teacher.llm.provider import LLMResponse, TokenUsage

        self._calls.append(messages)
        content = self._responses.pop(0) if self._responses else ""
        return LLMResponse(
            content=content,
            usage=TokenUsage(prompt_tokens=1, completion_tokens=1, total_tokens=2),
            model="scripted",
        )

    @property
    def context_window(self) -> int:
        return 100_000

    @property
    def max_tokens(self) -> int:
        return 16384

    @property
    def model_name(self) -> str:
        return "scripted"


def _chunk_response(start: int, count: int) -> str:
    """Build a mock LLM response documenting `count` endpoints starting at `start`."""
    return "\n".join(f"### GET /api/item-{start + i}\nDetail.\n" for i in range(count))


@pytest.mark.asyncio
async def test_generate_api_doc_preserves_all_endpoints(tmp_path):
    """Every endpoint in every chunk must appear in the generated markdown."""
    store, db = _make_store(tmp_path)
    try:
        total = API_CHUNK_SIZE * 3  # force at least 3 chunks
        endpoints = [
            APIEndpoint(
                method="GET",
                path=f"/api/item-{i}",
                handler=f"get_item_{i}",
                file="routes.py",
                description=f"Get item {i}",
            )
            for i in range(total)
        ]
        analysis = AnalysisResult(project_summary="t", api_endpoints=endpoints)

        # One well-formed response per chunk, covering all endpoints in order.
        scripted = [
            _chunk_response(i, API_CHUNK_SIZE)
            for i in range(0, total, API_CHUNK_SIZE)
        ]
        provider = _ScriptedProvider(scripted)

        path = await generate_api_doc(provider, analysis, store)
        content = path.read_text()

        for i in range(total):
            assert f"/api/item-{i}" in content, f"missing /api/item-{i}"
        # No extra retries when chunks are well-formed.
        assert len(provider._calls) == total // API_CHUNK_SIZE
    finally:
        db.close()


@pytest.mark.asyncio
async def test_generate_api_doc_retries_underproduced_chunk(tmp_path):
    """An empty first attempt on a chunk should trigger one retry."""
    store, db = _make_store(tmp_path)
    try:
        total = API_CHUNK_SIZE * 2  # 2 chunks
        endpoints = [
            APIEndpoint(
                method="GET",
                path=f"/api/item-{i}",
                handler=f"get_item_{i}",
                file="routes.py",
                description=f"Get item {i}",
            )
            for i in range(total)
        ]
        analysis = AnalysisResult(project_summary="t", api_endpoints=endpoints)

        # Chunk 1: good. Chunk 2: empty (triggers retry), then good.
        scripted = [
            _chunk_response(0, API_CHUNK_SIZE),
            "",  # chunk 2 first attempt: under-produced
            _chunk_response(API_CHUNK_SIZE, API_CHUNK_SIZE),  # retry
        ]
        provider = _ScriptedProvider(scripted)

        path = await generate_api_doc(provider, analysis, store)
        content = path.read_text()

        assert len(provider._calls) == 3, "expected 1 retry for the empty chunk"
        for i in range(total):
            assert f"/api/item-{i}" in content
    finally:
        db.close()


@pytest.mark.asyncio
async def test_generate_api_doc_survives_persistent_underproduction(tmp_path, capsys):
    """If both attempts on a chunk are empty, the other chunks still make it in."""
    store, db = _make_store(tmp_path)
    try:
        total = API_CHUNK_SIZE * 2
        endpoints = [
            APIEndpoint(
                method="GET",
                path=f"/api/item-{i}",
                handler=f"get_item_{i}",
                file="routes.py",
                description=f"Get item {i}",
            )
            for i in range(total)
        ]
        analysis = AnalysisResult(project_summary="t", api_endpoints=endpoints)

        # Chunk 1 succeeds, chunk 2 fails on both attempts.
        scripted = [
            _chunk_response(0, API_CHUNK_SIZE),
            "",
            "",
        ]
        provider = _ScriptedProvider(scripted)

        path = await generate_api_doc(provider, analysis, store)
        content = path.read_text()

        # Chunk 1 endpoints are present; chunk 2 endpoints are lost but the
        # generation did not crash, and the user saw a red warning.
        for i in range(API_CHUNK_SIZE):
            assert f"/api/item-{i}" in content
        captured = capsys.readouterr()
        combined = captured.out + captured.err
        assert "under-produced" in combined or "produced only" in combined
    finally:
        db.close()


@pytest.mark.asyncio
async def test_api_chunk_size_env_override(monkeypatch, tmp_path):
    """Setting CODEBASE_TEACHER_API_CHUNK_SIZE should change the chunk count."""
    import importlib
    import codebase_teacher.generator.docs as docs_mod

    monkeypatch.setenv("CODEBASE_TEACHER_API_CHUNK_SIZE", "3")
    importlib.reload(docs_mod)
    try:
        assert docs_mod.API_CHUNK_SIZE == 3
    finally:
        # Restore the normal default so other tests aren't affected.
        monkeypatch.delenv("CODEBASE_TEACHER_API_CHUNK_SIZE", raising=False)
        importlib.reload(docs_mod)


@pytest.mark.asyncio
async def test_generate_all_docs_includes_overview_first(mock_provider, tmp_path):
    store, db = _make_store(tmp_path)
    try:
        analysis = _make_analysis()

        paths, errors = await generate_all_docs(mock_provider, analysis, store)

        assert not errors

        names = [p.name for p in paths]
        # Overview must be first so CLI output presents it as the starting point
        assert names[0] == "overview.md"
        assert "architecture.md" in names
        assert "api-reference.md" in names
        assert "infrastructure.md" in names

        # All four files should exist on disk
        for p in paths:
            assert p.exists()
    finally:
        db.close()


@pytest.mark.asyncio
async def test_generate_all_docs_threads_learner_info(mock_provider, tmp_path):
    """Learner info must reach every doc-generator LLM call."""
    store, db = _make_store(tmp_path)
    try:
        analysis = _make_analysis()
        analysis.learner_info = "I only care about the signup flow."

        paths, errors = await generate_all_docs(mock_provider, analysis, store)
        assert not errors

        # Every recorded user message should carry the learner preamble.
        for call in mock_provider._calls:
            user_msg = call[-1].content
            assert "Learner Context" in user_msg
            assert "signup flow" in user_msg
    finally:
        db.close()


@pytest.mark.asyncio
async def test_generate_overview_doc_without_learner_info_no_preamble(
    mock_provider, tmp_path
):
    """Default empty learner_info means no preamble is injected."""
    store, db = _make_store(tmp_path)
    try:
        analysis = _make_analysis()  # learner_info defaults to ""

        await generate_overview_doc(mock_provider, analysis, store)

        user_msg = mock_provider._calls[-1][-1].content
        assert "Learner Context" not in user_msg
    finally:
        db.close()
