"""Tests for the documentation generator, including the overview ('Start Here') page."""

from __future__ import annotations

import pytest

from codebase_teacher.generator.docs import (
    generate_all_docs,
    generate_overview_doc,
)
from codebase_teacher.storage.artifact_store import ArtifactStore
from codebase_teacher.storage.database import Database
from codebase_teacher.storage.models import (
    AnalysisResult,
    APIEndpoint,
    DataFlow,
    InfraComponent,
)


def _make_store(tmp_path) -> tuple[ArtifactStore, Database]:
    db = Database(tmp_path / "test.db")
    project_id = db.get_or_create_project(str(tmp_path), "test_project")
    store = ArtifactStore(tmp_path / "output", db, project_id)
    return store, db


def _make_analysis() -> AnalysisResult:
    return AnalysisResult(
        project_summary="A small Flask API that manages users and sends welcome emails.",
        module_summaries={
            "app.py": "Flask entry point. Wires routes to user handlers.",
            "users.py": "User CRUD logic backed by PostgreSQL.",
            "tasks.py": "Celery tasks for sending emails.",
        },
        api_endpoints=[
            APIEndpoint(
                method="POST",
                path="/api/users",
                handler="create_user",
                file="users.py",
                description="Create a new user",
            ),
        ],
        infrastructure=[
            InfraComponent(
                type="database",
                technology="PostgreSQL",
                explanation="Relational database.",
                usage="Stores user records.",
                config="DATABASE_URL env var",
            ),
        ],
        data_flows=[
            DataFlow(
                name="User signup",
                entry_points=["POST /api/users"],
                steps=["Validate input", "Insert into DB", "Enqueue welcome email"],
                outputs=["DB write", "Celery task"],
            ),
        ],
    )


@pytest.mark.asyncio
async def test_generate_overview_doc_writes_start_here_page(mock_provider, tmp_path):
    store, db = _make_store(tmp_path)
    try:
        analysis = _make_analysis()

        path = await generate_overview_doc(mock_provider, analysis, store)

        assert path.exists()
        assert path.name == "overview.md"
        assert path.parent.name == "docs"

        content = path.read_text()
        # Template wraps the body with a title and footer
        assert "# Start Here" in content
        assert "Generated by codebase-teacher" in content
    finally:
        db.close()


@pytest.mark.asyncio
async def test_generate_overview_doc_passes_context_to_llm(mock_provider, tmp_path):
    store, db = _make_store(tmp_path)
    try:
        analysis = _make_analysis()

        await generate_overview_doc(mock_provider, analysis, store)

        # The provider should have been called with the project summary and
        # references to the other docs/surfaces so the LLM can point readers to them.
        assert len(mock_provider._calls) == 1
        user_msg = mock_provider._calls[0][-1].content
        assert "Flask API" in user_msg
        assert "PostgreSQL" in user_msg
        assert "POST /api/users" in user_msg
        # Prompt should steer the model toward a friendly 'Start Here' structure
        assert "Start Here" in user_msg or "start here" in user_msg.lower()
        assert "architecture.md" in user_msg
    finally:
        db.close()


@pytest.mark.asyncio
async def test_generate_overview_doc_handles_empty_analysis(mock_provider, tmp_path):
    store, db = _make_store(tmp_path)
    try:
        analysis = AnalysisResult()  # everything empty / default

        path = await generate_overview_doc(mock_provider, analysis, store)

        assert path.exists()
        content = path.read_text()
        assert "# Start Here" in content
    finally:
        db.close()


@pytest.mark.asyncio
async def test_generate_all_docs_includes_overview_first(mock_provider, tmp_path):
    store, db = _make_store(tmp_path)
    try:
        analysis = _make_analysis()

        paths, errors = await generate_all_docs(mock_provider, analysis, store)

        assert not errors

        names = [p.name for p in paths]
        # Overview must be first so CLI output presents it as the starting point
        assert names[0] == "overview.md"
        assert "architecture.md" in names
        assert "api-reference.md" in names
        assert "infrastructure.md" in names

        # All four files should exist on disk
        for p in paths:
            assert p.exists()
    finally:
        db.close()
